/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.controlegastos.front.view;

import java.awt.Color;
import java.awt.Graphics;
import java.beans.PropertyVetoException;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Rodrigo
 */
public class TelaControleGrafico extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaControleGrafico
     */
    public TelaControleGrafico() throws PropertyVetoException {
        initComponents();
        
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        setMaximum(true);
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.addValue(520, "Corolla", "Gasto");
        dataset.addValue(320, "Ford Ka", "Gasto");
        dataset.addValue(130, "Intruder", "Gasto");
        dataset.addValue(789, "RAM 2500", "Gasto");

        // Criar o gráfico de barras
        JFreeChart chart = ChartFactory.createBarChart3D("Controle de Gastos", "Categoria", "Valor", dataset, PlotOrientation.VERTICAL, true, true, false);

        // Criar o painel do gráfico
        ChartPanel chartPanel = new ChartPanel(chart);
                
        // Criar o JFrame e adicionar o painel do gráfico
        JFrame frame = new JFrame("Dashboard Controle de Gastos");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(910, 520);
        frame.getContentPane().add(chartPanel);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controlegastos/front/image/fundo.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 910, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
