/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.controlegastos.front.view;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Rodrigo
 */
public class TelaHomeSwing extends javax.swing.JFrame {

    /**
     * Creates new form TelaHomeSwing
     */
    //private JDesktopPane desktopPane;
    public TelaHomeSwing() {
        initComponents();

        // Define o tamanho da tela
        int largura = 910;
        int altura = 600;
        this.setSize(largura, altura);
        setLocationRelativeTo(null);

        // Impede que a tela possa ser redimensionada pelo usuário
        this.setResizable(false);

        // Define o comportamento ao fechar a tela
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabelSair = new javax.swing.JLabel();
        jLabelRelatorio = new javax.swing.JLabel();
        jLabelVeiculo = new javax.swing.JLabel();
        jLabelProprietario = new javax.swing.JLabel();
        jLabelControle = new javax.swing.JLabel();
        jLabelFundoTopBar = new javax.swing.JLabel();
        jDesktopPaneTelas = new javax.swing.JDesktopPane();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabelSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controlegastos/front/image/sair.png"))); // NOI18N
        jLabelSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSairMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelSair);
        jLabelSair.setBounds(790, 20, 116, 50);

        jLabelRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controlegastos/front/image/relatorio.png"))); // NOI18N
        getContentPane().add(jLabelRelatorio);
        jLabelRelatorio.setBounds(630, 20, 116, 50);

        jLabelVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controlegastos/front/image/veiculo.png"))); // NOI18N
        jLabelVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVeiculoMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVeiculo);
        jLabelVeiculo.setBounds(340, 20, 116, 50);

        jLabelProprietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controlegastos/front/image/proprietario.png"))); // NOI18N
        jLabelProprietario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProprietarioMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelProprietario);
        jLabelProprietario.setBounds(190, 20, 116, 50);

        jLabelControle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controlegastos/front/image/controle.gif"))); // NOI18N
        jLabelControle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelControleMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelControle);
        jLabelControle.setBounds(490, 20, 116, 50);

        jLabelFundoTopBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controlegastos/front/image/imageLogo.png"))); // NOI18N
        getContentPane().add(jLabelFundoTopBar);
        jLabelFundoTopBar.setBounds(0, 0, 910, 80);
        getContentPane().add(jDesktopPaneTelas);
        jDesktopPaneTelas.setBounds(0, 80, 910, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVeiculoMouseClicked
        // TODO add your handling code here:
        TelaVeiculo telaVeiculo;
        try {
            telaVeiculo = new TelaVeiculo();
            telaVeiculo.setVisible(true);
            jDesktopPaneTelas.add(telaVeiculo);

        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaHomeSwing.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabelVeiculoMouseClicked

    private void jLabelProprietarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProprietarioMouseClicked
        // TODO add your handling code here:
        TelaProprietario telaProprietario;
        try {
            telaProprietario = new TelaProprietario();
            telaProprietario.setVisible(true);
            jDesktopPaneTelas.add(telaProprietario);

        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaHomeSwing.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelProprietarioMouseClicked

    private void jLabelSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSairMouseClicked

    private void jLabelControleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelControleMouseClicked
        // TODO add your handling code here:
        TelaControleGasto telaGastos;
        try {
            telaGastos = new TelaControleGasto();
            telaGastos.setVisible(true);
            jDesktopPaneTelas.add(telaGastos);

        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaHomeSwing.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelControleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHomeSwing.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHomeSwing.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHomeSwing.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHomeSwing.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHomeSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDesktopPane jDesktopPaneTelas;
    private javax.swing.JLabel jLabelControle;
    private javax.swing.JLabel jLabelFundoTopBar;
    private javax.swing.JLabel jLabelProprietario;
    private javax.swing.JLabel jLabelRelatorio;
    private javax.swing.JLabel jLabelSair;
    private javax.swing.JLabel jLabelVeiculo;
    // End of variables declaration//GEN-END:variables
}
